name: build-and-push

on:
  push:
    branches:
      - "main"

jobs:
  update-versions:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Generate Tag
        id: generate_tag
        uses: anothrNick/github-tag-action@1.38.0
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          DRY_RUN: true

      # Set Up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      # Lint
      - name: Helm Lint
        run: |
          helm lint deploy

      # Publish helm chart
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          branch: main
          repository: charts
          target_dir: docs
          token: ${{ secrets.AUTH_TOKEN }}
          charts_dir: .
          charts_url: https://osamakhan220.github.io/charts/
          owner: osamakhan220
          linting: off
          commit_username: osamakhan220
          commit_email: osama@stakater.com

      - name: Check out remote code
        uses: actions/checkout@v2
        with:
          repository: "OsamaKhan220/us-apps-gitops"
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: "Update Chart"
        run: |
          echo "Before changes"
          cat user-services/ldap/dev/Chart.yaml
          cat user-services/ldap/dev/values.yaml
          yq -i '.dependencies[0].version = "${{ steps.generate_tag.outputs.new_tag }}"' user-services/ldap/dev/Chart.yaml
          yq -i '.version = "${{ steps.generate_tag.outputs.new_tag }}"' user-services/ldap/dev/Chart.yaml
          yq -i '.ldap-helm.application.deployment.image.tag = "${{ steps.generate_tag.outputs.new_tag }}"' user-services/ldap/dev/values.yaml
          echo "After changes"
          cat user-services/ldap/dev/Chart.yaml
          cat user-services/ldap/dev/values.yaml
          echo "File updated"

      # Commit back change
      - name: Commit files
        run: |
          git config --local user.email "osama@stakater.com"
          git config --local user.name "OsamaKhan220"
          git status
          git diff
          git add .
          git commit -m "Update chart to ${{ steps.generate_tag.outputs.new_tag }}" -a

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          repository-name: "OsamaKhan220/us-apps-gitops"
          branch: main
          target-folder: "user-services/ldap/dev"
          folder: "user-services/ldap/dev"
